version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      # Install Maven
      echo Installing Maven...
      yum install -y maven
  pre_build:
    commands:
      # Set up any environment variables or commands needed before the build
      echo Preparing to build the project...
  build:
    commands:
      # Run Maven build
      echo Building the project with Maven...
      mvn clean install
      # List contents of the target directory to ensure the JAR is being created
      ls -l target/
  post_build:
    commands:
      # You can add any post-build actions, such as packaging or uploading artifacts
      echo Build completed. Ready for deployment.

artifacts:
  files:
    - target/*.jar  # Specify the JAR file generated after build
